[package]
name = "string_enum"
version = "0.1.0"
authors = ["강동윤 <kdy1@outlook.kr>"]

[lib]
proc-macro = true

[dependencies]
swc_macros_common = { path = "../common" }
pmutil = "0.2"
proc-macro2 = "0.4.4"
quote = "0.6.3"

[dependencies.syn]
version = "0.14.1"
features = ["full", "parsing", "printing", "extra-traits"]


