[workspace]

[package]
name = "swc"
version = "0.1.0"
authors = ["강동윤 <kdy1@outlook.kr>"]

[dependencies]
libswc = { path = "./swc" }
swc_common = { path = "./common" }

rayon = "0.9"
slog = "2"
slog-envlogger = "2.1"
slog-term = "2.3"


[dependencies.clap]
version = "2.29"
default-features = false
features = [ "suggestions", "color" ]


[profile.bench]
debug = true