[package]
name = "libswc"
version = "0.1.0"
authors = ["강동윤 <kdy1@outlook.kr>"]

[lib]
name = "swc"

[dependencies]
swc_atoms = { path = "../atoms" }
swc_ecmascript = { path = "../ecmascript" }
swc_common = { path = "../common" }
swc_macros = { path = "../macros" }
rayon = "0.9"
slog = "2"