[package]
name = "ast_node"
version = "0.1.0"
authors = ["강동윤 <kdy1@outlook.kr>"]

[lib]
proc-macro = true

[dependencies]
swc_macros_common = { path = "../common" }
pmutil = "0.1"
proc-macro2 = { version = "0.2", features = ["nightly"] }
quote = "0.4"
darling = "0.3"

[dependencies.syn]
version = "0.12"
features = ["derive", "fold", "parsing", "printing"]


[dev-dependencies]
swc_macros = { path = "../" }
swc_common = { path = "../../common" }