[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "Quasi quotation system for ecmascript"
documentation = "https://rustdoc.swc.rs/swc_ecma_quote/"
edition       = "2021"
license       = "Apache-2.0"
name          = "swc_ecma_quote"
repository    = "https://github.com/swc-project/swc.git"
version       = "0.32.1"

[lib]
bench = false

[dependencies]
swc_atoms             = { version = "0.4.2", path = "../swc_atoms" }
swc_common            = { version = "0.27.3", path = "../swc_common" }
swc_ecma_ast          = { version = "0.90.4", path = "../swc_ecma_ast" }
swc_ecma_quote_macros = { version = "0.28.1", path = "../swc_ecma_quote_macros" }
swc_ecma_utils        = { version = "0.99.1", path = "../swc_ecma_utils" }

[dev-dependencies]
testing = { version = "0.29.1", path = "../testing" }
