[package]
name = "swc_common"
version = "0.1.0"
authors = ["강동윤 <kdy1@outlook.kr>"]

[dependencies]
atty = "0.2"
fnv = "1"
string_cache = "0.6"
either = "1.4"
rustc-ap-rustc_errors = "150"
rustc-ap-rustc_data_structures = "150"
rustc-ap-syntax_pos = "150"
swc_macros = { path = "../macros" }