[package]
authors       = ["강동윤 <kdy1997.dev@gmail.com>"]
description   = "CSS minifier"
documentation = "https://rustdoc.swc.rs/swc_css_minifier/"
edition       = "2021"
include       = ["Cargo.toml", "src/**/*.rs"]
license       = "Apache-2.0"
name          = "swc_css_minifier"
repository    = "https://github.com/swc-project/swc.git"
version       = "0.81.0"

[lib]
bench = false

[dependencies]
serde         = "1.0.118"
swc_atoms     = { version = "0.4.3", path = "../swc_atoms" }
swc_common    = { version = "0.27.4", path = "../swc_common" }
swc_css_ast   = { version = "0.106.0", path = "../swc_css_ast" }
swc_css_utils = { version = "0.103.0", path = "../swc_css_utils/" }
swc_css_visit = { version = "0.105.0", path = "../swc_css_visit" }

[dev-dependencies]
swc_css_codegen = { version = "0.116.0", path = "../swc_css_codegen" }
swc_css_parser  = { version = "0.115.0", path = "../swc_css_parser" }
testing         = { version = "0.29.2", path = "../testing" }
